'use strict';
const {rememberOrderPlaces}=require('./src/services/addressBook.js');
const crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');
const fs=require('node:fs'),path=require('node:path');
const dir=process.env.WASEL_DATA_DIR||path.join(__dirname,'data');fs.mkdirSync(dir,{recursive:true});
const db=new DatabaseSync(path.join(dir,'wasel.sqlite'));db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;');
db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,phone TEXT,role TEXT,password TEXT,profile TEXT,approved INTEGER DEFAULT 0,UNIQUE(phone,role));
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,merchant TEXT,courier TEXT,status TEXT,body TEXT);
CREATE TABLE IF NOT EXISTS records(id TEXT PRIMARY KEY,kind TEXT,owner TEXT,order_id TEXT,body TEXT);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT,expires INTEGER);
CREATE TABLE IF NOT EXISTS config(id INTEGER PRIMARY KEY,body TEXT);`);
const statuses={draft:'محفوظ',published:'منشور',reserved:'بانتظار المندوب',approaching:'المندوب في الطريق إلى التاجر',arrived:'المندوب وصل',waiting:'بانتظار الاستلام',received:'تم الاستلام',transit:'قيد التوصيل',at_customer:'وصل إلى الزبون',delivered:'تم التسليم',failed:'تعذر التسليم',retry:'إعادة محاولة التوصيل',return_pending:'بانتظار الإرجاع',returning:'قيد الإرجاع',returned:'تم الإرجاع',cancelled:'ملغي',partial_pending:'تسليم جزئي — بانتظار إرجاع المتبقي'};
const before=['draft','published','reserved','approaching','arrived','waiting'];
const custody=['received','transit','at_customer','failed','retry','return_pending','returning','partial_pending'];
const closed=['delivered','returned','cancelled'];
const defaults={freeService:true,commission:0,subscription:0,offerAfterMinutes:15,arrivalBuffer:40,extensionPercent:50,preparationMinutes:20,cancelSecondMinutes:60,cancelThirdMinutes:180,maxAttempts:3,motivationMinutes:60,maxLoads:{motorcycle:3,sedan:6,truck:15,refrigerated:8},vehicleKg:{motorcycle:15,sedan:100,truck:1500,refrigerated:800},vehicleCm:{motorcycle:70,sedan:150,truck:400,refrigerated:300},vipExclusive:true,partialEnabled:false,vipSurcharge:3000};
const fail=(message,status=400)=>{throw Object.assign(Error(message),{status});};
const now=()=>new Date().toISOString();
const id=prefix=>prefix+'-'+crypto.randomBytes(5).toString('hex').toUpperCase();
const clean=(x,max=200)=>String(x??'').trim().slice(0,max);
function phone(value,restricted=true){let p=String(value||'').replace(/[٠-٩]/g,c=>'٠١٢٣٤٥٦٧٨٩'.indexOf(c)).replace(/[\s()+-]/g,'');if(p.startsWith('00964'))p='0'+p.slice(5);else if(p.startsWith('964'))p='0'+p.slice(3);if(!(restricted?/^07[789]\d{8}$/:/^07\d{9}$/).test(p))fail(restricted?'رقم الحساب يجب أن يبدأ بـ077 أو078 أو079 ويتكون من11 رقماً.':'رقم الهاتف العراقي غير صحيح.');return p;}
function hash(password,salt=crypto.randomBytes(16).toString('hex')){return salt+':'+crypto.scryptSync(password,salt,32).toString('hex');}
function check(password,stored){const computed=hash(password,stored.split(':')[0]);return crypto.timingSafeEqual(Buffer.from(computed),Buffer.from(stored));}
function user(uid){const r=db.prepare('SELECT * FROM users WHERE id=?').get(uid);return r?{id:r.id,phone:r.phone,role:r.role,approved:!!r.approved,...JSON.parse(r.profile)}:null;}
function users(){return db.prepare('SELECT id FROM users').all().map(r=>user(r.id));}
function writeUser(u){const {id:uid,phone:p,role,approved,...profile}=u;db.prepare('UPDATE users SET profile=?,approved=? WHERE id=?').run(JSON.stringify(profile),approved?1:0,uid);}
function order(oid){const r=db.prepare('SELECT body FROM orders WHERE id=?').get(oid);if(!r)fail('الطلب غير موجود',404);return JSON.parse(r.body);}
function orders(){return db.prepare('SELECT body FROM orders').all().map(r=>JSON.parse(r.body));}
function writeOrder(o){db.prepare('INSERT INTO orders VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET merchant=excluded.merchant,courier=excluded.courier,status=excluded.status,body=excluded.body').run(o.id,o.merchant,o.courier||null,o.status,JSON.stringify(o));}
function record(kind,owner,oid,body){const r={id:id('EV'),at:now(),...body};db.prepare('INSERT INTO records VALUES(?,?,?,?,?)').run(r.id,kind,owner||'',oid||'',JSON.stringify(r));return r;}
function records(kind){return db.prepare('SELECT owner,order_id,body FROM records WHERE kind=? ORDER BY rowid DESC').all(kind).map(r=>({...JSON.parse(r.body),owner:r.owner,orderId:r.order_id}));}
function config(){return {...defaults,...JSON.parse(db.prepare('SELECT body FROM config WHERE id=1').get()?.body||'{}')};}
function note(uid,o,text){if(uid)record('notification',uid,o?.id,{text});}
function scan(o,u,kind,method){const text=kind==='pickup'?'تم التحقق من رمز الاستلام':'تم التحقق من رمز المرتجع';o.history.push({at:now(),actor:u.id,status:o.status,action:'scan',kind,method:method==='qr'?'qr':'manual',text:text+(method==='qr'?' عبر QR':' يدوياً')});}
function log(o,u,text){o.history.push({at:now(),actor:u.id,text,status:o.status});record('audit',u.id,o.id,{text,status:o.status});}
function change(o,u,status,text){o.status=status;log(o,u,text);note(o.merchant,o,text);if(o.courier)note(o.courier,o,text);}
function amount(v,label='المبلغ',max=100000000){const n=Number(v);if(!Number.isSafeInteger(n)||n<0||n>max)fail(label+' غير صحيح');return n;}
function tx(fn){db.exec('BEGIN IMMEDIATE');try{const value=fn();db.exec('COMMIT');return value;}catch(e){db.exec('ROLLBACK');throw e;}}
function wallet(uid){return records('wallet').filter(r=>r.owner===uid).reduce((n,r)=>n+r.amount,0);}
function unresolved(uid){return orders().some(o=>(o.merchant===uid||o.courier===uid)&&o.status!=='draft'&&(!closed.includes(o.status)||!o.settled));}
function distance(a,b){const r=x=>x*Math.PI/180;const dlat=r(a.lat-b.lat),dlng=r(a.lng-b.lng);return 6371*2*Math.asin(Math.min(1,Math.sqrt(Math.sin(dlat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dlng/2)**2)));}
function location(p){const lat=Number(p?.lat),lng=Number(p?.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<29||lat>38||lng<38||lng>49)fail('حدد موقعاً صحيحاً داخل العراق.');return {lat,lng};}
function canSee(u,o){return o.merchant===u.id||o.courier===u.id||(u.role==='courier'&&o.status==='published'&&eligible(u,o));}
function eligible(u,o){const c=config(),v=u.vehicle||'motorcycle';return u.approved&&u.available&&u.location&&o.sender?.location&&o.vehicle===v&&Number(u.budget)>=(o.kind==='free'?0:o.amount)&&o.weight<=c.vehicleKg[v]&&Math.max(o.length,o.width,o.height)<=c.vehicleCm[v]&&distance(u.location,o.sender.location)<=u.radius;}
function redact(u,o){const result=structuredClone(o);if(u.role==='courier'&&!custody.includes(o.status)&&!closed.includes(o.status)){result.recipient={province:o.recipient.province,area:o.recipient.area};delete result.notes;delete result.photo;}if(u.role==='courier')delete result.handoverCode;if(u.id!==o.merchant)delete result.returnCode;return result;}
function publicUser(u){const result=structuredClone(u);delete result.photos;delete result.documents;return result;}
function expire(){tx(()=>{for(const o of orders()){
 if(!['reserved','approaching'].includes(o.status)||!o.deadline)continue;
 const remaining=Date.parse(o.deadline)-Date.now();
 if(remaining<=0){const courier=o.courier;o.courier=null;o.courierInfo=null;o.handoverCode=null;o.deadline=null;o.extensionRequest=null;o.publishedAt=now();change(o,{id:'SYSTEM'},'published','انتهت مهلة الوصول؛ أعيد نشر الطلب');note(courier,o,'انتهى الحجز لعدم تأكيد الوصول');writeOrder(o);}
 else if(remaining<=120000&&o.arrivalWarnedDeadline!==o.deadline){note(o.courier,o,'باقي دقيقتين أو أقل للوصول؛ اختر التمديد ضمن الحد المتاح');o.arrivalWarnedDeadline=o.deadline;writeOrder(o);}
}});}
function view(u){expire();u=user(u.id);const visible=orders().filter(o=>canSee(u,o));const people=users();const c=config();
 if(u.motivational!==false){const recent=records('notification').find(n=>n.owner===u.id&&n.motivational);if(!recent||Date.now()-Date.parse(recent.at)>c.motivationMinutes*60000){const nearby=u.role==='courier'&&!u.available&&orders().some(o=>o.status==='published'&&eligible({...u,available:true},o));const drafts=u.role==='merchant'&&visible.some(o=>o.status==='draft')&&people.some(p=>p.role==='courier'&&p.available&&p.location&&distance(p.location,u.location)<=5);if(nearby||drafts)record('notification',u.id,'',{text:nearby?'توجد طلبات قريبة تناسب مركبتك وميزانيتك؛ يمكنك العودة إلى متاح.':'يوجد مندوب متاح قربك ولديك طلبات محفوظة غير منشورة.',motivational:true});}}
 return {user:publicUser(u),settings:c,statuses,orders:visible.map(o=>redact(u,o)),notifications:records('notification').filter(r=>r.owner===u.id).slice(0,60),ledger:records('wallet').filter(r=>r.owner===u.id),cashLedger:records('cash').filter(r=>r.owner===u.id),balance:wallet(u.id),ratings:records('rating').filter(r=>r.target===u.id||r.owner===u.id),couriers:u.role==='merchant'?people.filter(p=>p.role==='courier'&&p.approved&&p.available&&p.location&&distance(p.location,u.location)<=20).map(p=>({id:p.id,name:p.name,vehicle:p.vehicle,plate:p.plate,location:p.location,locationAt:p.locationAt,phone:visible.some(o=>o.courier===p.id)?p.phone:null})):[],offers:records('offer').filter(r=>visible.some(o=>o.id===r.orderId)),profileLocked:unresolved(u.id),messages:records('chat').filter(r=>visible.some(o=>o.id===r.orderId&&(o.merchant===u.id||o.courier===u.id)))};}
function normalizeOrder(data,u,old){
 const c=config();const kind=data.kind==='free'?'free':'merchant';const sender=kind==='free'?{name:clean(data.sender?.name,80),phone:phone(data.sender?.phone),address:clean(data.sender?.address),province:u.province,location:location(data.sender?.location)}:{name:u.name,phone:u.phone,phone2:u.phone2||'',province:u.province,area:clean(data.sender?.area||u.area,80),address:clean(data.sender?.address||u.address),location:data.sender?.location?location(data.sender.location):u.location};
 if(!sender.name||!sender.address)fail('أكمل بيانات المرسل.');
 const r=data.recipient||{};const recipient={name:clean(r.name,80),phone:phone(r.phone,false),phone2:r.phone2?phone(r.phone2,false):'',province:u.province,area:clean(r.area,80),address:clean(r.address),landmark:clean(r.landmark),location:r.location?location(r.location):null};
 if(!recipient.name||!recipient.area||!recipient.address)fail('أكمل اسم المستلم والمنطقة والعنوان.');
 const fee=amount(data.fee,'أجرة التوصيل',1000000),returnFee=amount(data.returnFee,'أجرة الراجع',1000000);if(returnFee>fee)fail('أجرة الراجع يجب أن تساوي أجرة التوصيل أو تقل عنها.');
 const vehicle=data.vehicle,nature=data.nature;if(!['motorcycle','sedan','truck','refrigerated'].includes(vehicle)||!['normal','fragile','food','cold'].includes(nature))fail('حدد المركبة وطبيعة الشحنة.');if(nature==='cold'&&vehicle!=='refrigerated')fail('الشحنة المبردة تحتاج سيارة مبردة.');
 const count=amount(data.count,'عدد القطع',1000);if(count<1)fail('عدد القطع يجب أن يكون واحداً على الأقل.');const sizes={};for(const field of ['weight','length','width','height']){sizes[field]=Number(data[field]);if(!Number.isFinite(sizes[field])||sizes[field]<=0||sizes[field]>10000)fail('أدخل وزن وأبعاد الشحنة بصورة صحيحة.');}
 if(sizes.weight>c.vehicleKg[vehicle]||Math.max(sizes.length,sizes.width,sizes.height)>c.vehicleCm[vehicle])fail('وزن الشحنة أو أبعادها يتجاوز سعة المركبة المحددة.');
 const service=data.service==='vip'?'vip':'normal';const baseFee=amount(data.baseFee??fee,'الأجرة العادية',1000000);if(service==='vip'&&fee<baseFee+c.vipSurcharge)fail('أجرة VIP يجب أن تشمل الزيادة المحددة فوق الأجرة العادية.');
 const value=kind==='free'&&data.collection==='none'?0:amount(data.amount,'قيمة البضاعة');
 if(kind==='free'&&!/^data:image\/(jpeg|png|webp);base64,/.test(data.photo||''))fail('التوصيل الحر يحتاج صورة للشحنة من الكاميرا.');
 return {...old,id:old?.id||id('ORD'),merchant:u.id,status:old?.status||'draft',courier:old?.courier||null,createdAt:old?.createdAt||now(),kind,sender,recipient,amount:value,count,...sizes,nature,vehicle,fee,baseFee,returnFee,feePayer:data.feePayer==='merchant'?'merchant':'customer',service,notes:clean(data.notes,500),photo:kind==='free'?data.photo:null,collection:kind==='free'?data.collection:'goods',settled:false,history:old?.history||[],attempts:old?.attempts||0};
}
function access(u,o,role){if(role&&u.role!==role)fail('هذا الإجراء غير متاح لهذا الدور',403);if(!canSee(u,o))fail('غير مصرح بهذا الطلب',403);}
function must(condition,message){if(!condition)fail(message);}
function cash(o,uid,value,reason){record('cash',uid,o.id,{amount:value,reason,goods:o.amount,deliveryFee:o.fee,returnFee:o.returnFee});}
function commission(o){const c=config();if(!c.freeService&&c.commission)record('wallet',o.merchant,o.id,{amount:-c.commission,reason:'عمولة طلب مكتمل'});}
function action(u,oid,action,p={}){expire();return tx(()=>{
 u=user(u.id);must(u.approved,'الحساب غير نشط.');const o=order(oid);access(u,o);const c=config();const own=o.merchant===u.id,assigned=o.courier===u.id;
 if(action==='edit'){must(own&&before.includes(o.status),'لا يمكن تعديل الطلب بعد استلامه.');const prevCourier=o.courier;const changed=normalizeOrder(p,u,o);changed.courier=null;changed.handoverCode=null;changed.status=o.status==='draft'?'draft':'published';changed.publishedAt=now();log(changed,u,prevCourier?'عُدّل الطلب وأُلغي الحجز السابق وأعيد نشره دون احتساب إلغاء على المندوب':'عُدّل الطلب');note(prevCourier,o,'ألغى التاجر الحجز بسبب تعديل بيانات الطلب');const current=user(u.id);rememberOrderPlaces(current,changed,id);writeUser(current);writeOrder(changed);return changed;}
 if(action==='publish'){must(own&&o.status==='draft','يمكن نشر الطلب المحفوظ فقط.');change(o,u,'published','نُشر الطلب');o.publishedAt=now();}
 else if(action==='unpublish'){must(own&&o.status==='published','يمكن إلغاء نشر الطلب غير المحجوز فقط.');change(o,u,'draft','أُلغي نشر الطلب');}
 else if(action==='delete'){must(own&&o.status==='draft','الحذف متاح للطلبات المحفوظة فقط.');db.prepare('DELETE FROM orders WHERE id=?').run(oid);record('audit',u.id,oid,{text:'حذف طلب محفوظ'});return {deleted:true};}
 else if(action==='cancel'){must(own&&before.includes(o.status),'بعد الاستلام يجب التسليم أو الإرجاع والتسوية.');change(o,u,'cancelled','ألغى التاجر الطلب قبل الاستلام');o.settled=true;}
 else if(action==='raise_fee'){must(own&&o.status==='published','زيادة الأجرة للطلبات المنشورة فقط.');const fee=amount(p.fee);must(fee>o.fee,'أدخل أجرة أعلى من الحالية');o.fee=fee;log(o,u,'رفع التاجر أجرة التوصيل');}
 else if(action==='offer'){must(u.role==='courier'&&o.status==='published','العرض متاح للطلبات المنشورة');must(Date.now()-Date.parse(o.publishedAt)>=c.offerAfterMinutes*60000,'لم تبدأ مهلة العروض بعد');const fee=amount(p.fee);must(fee>0&&fee>=o.returnFee,'الأجرة المقترحة يجب أن تغطي أجرة الراجع');record('offer',u.id,o.id,{fee,name:u.name});note(o.merchant,o,'وصل عرض أجرة بديلة');return {offered:true};}
 else if(action==='reserve'||action==='accept_offer'){
  let courier=u;if(action==='accept_offer'){must(own&&o.status==='published','الطلب لم يعد متاحاً');const offer=records('offer').find(x=>x.id===p.offer&&x.orderId===oid);must(offer,'العرض غير موجود');courier=user(offer.owner);o.fee=offer.fee;}
  must(courier.role==='courier'&&o.status==='published','الطلب محجوز أو غير متاح');must(eligible(courier,o),'الطلب خارج النطاق أو لا يناسب المركبة أو الميزانية');must(!courier.restrictedUntil||Date.parse(courier.restrictedUntil)<Date.now(),'الحجوزات الجديدة مقيّدة مؤقتاً');
  const carried=orders().filter(x=>x.courier===courier.id&&!closed.includes(x.status));must(!carried.some(x=>before.includes(x.status)),'استلم الحجز الأول قبل حجز طلب آخر');must(carried.length<c.maxLoads[courier.vehicle],'وصلت إلى حد الطلبات المحمولة');must(!carried.some(x=>x.service==='vip')&&!(o.service==='vip'&&c.vipExclusive&&carried.length),'المندوب مخصص لطلب VIP أو يحمل طلباً آخر');
  o.courier=courier.id;o.courierInfo={id:courier.id,name:courier.name,phone:courier.phone,vehicle:courier.vehicle,plate:courier.plate,photo:courier.photos?.[0]||null};o.pickupDistanceKm=distance(courier.location,o.sender.location);o.originalMinutes=Math.max(3,Math.ceil(o.pickupDistanceKm*3*(1+c.arrivalBuffer/100)));o.deadline=new Date(Date.now()+o.originalMinutes*60000).toISOString();o.extended=false;o.extensionMinutes=0;o.handoverCode=String(crypto.randomInt(100000,1000000));change(o,u,'reserved','حُجز الطلب للمندوب '+courier.name);
 }
 else if(action==='depart'){must(assigned&&o.status==='reserved','إجراء غير متاح');change(o,u,'approaching','المندوب في الطريق إلى التاجر');}
 else if(action==='extend'){must(assigned&&['reserved','approaching'].includes(o.status)&&Date.parse(o.deadline)>Date.now(),'انتهت مهلة الحجز أو تم الوصول');const used=o.extensionMinutes??(o.extended?Math.ceil(o.originalMinutes/2):0);const minutes=Number(p.minutes);must(Number.isInteger(minutes)&&minutes>=1&&minutes<=Math.ceil(o.originalMinutes/2)-used,'تجاوزت الحد المتبقي للتمديد');o.deadline=new Date(Date.parse(o.deadline)+minutes*60000).toISOString();o.extensionMinutes=used+minutes;o.extended=true;log(o,u,'مُددت مهلة الوصول '+minutes+' دقيقة');note(o.merchant,o,'مدد المندوب مهلة الوصول');}
 else if(action==='release'){must(assigned&&['reserved','approaching','arrived','waiting'].includes(o.status),'لا يمكن إلغاء الحجز بعد استلام الشحنة');must(clean(p.reason),'حدد سبب إلغاء الحجز');record('cancellation',u.id,oid,{reason:clean(p.reason)});const count=records('cancellation').filter(x=>x.owner===u.id&&x.at.slice(0,10)===now().slice(0,10)).length;if(count>=2){u.restrictedUntil=new Date(Date.now()+(count===2?c.cancelSecondMinutes:c.cancelThirdMinutes)*60000).toISOString();writeUser(u);}o.courier=null;o.handoverCode=null;change(o,u,'published','ألغى المندوب الحجز: '+clean(p.reason));o.publishedAt=now();}
 else if(action==='arrive'){must(assigned&&['reserved','approaching'].includes(o.status),'إجراء غير متاح');o.deadline=null;change(o,u,'arrived','وصل المندوب إلى موقع الاستلام');o.preparationDeadline=new Date(Date.now()+c.preparationMinutes*60000).toISOString();}
 else if(action==='wait'){must(assigned&&o.status==='arrived','إجراء غير متاح');change(o,u,'waiting','الشحنة بانتظار التجهيز أو معالجة الاختلاف');}
 else if(action==='pickup'){
  must(assigned&&['arrived','waiting'].includes(o.status),'أكد الوصول أولاً');must(p.inspected===true&&p.paid===true,'يجب تأكيد الفحص والدفع قبل الاستلام');must(p.code===o.handoverCode,'رمز الاستلام غير صحيح');const prepaid=o.kind==='free'?0:o.amount;must(u.budget>=prepaid,'الميزانية لا تكفي لدفع قيمة البضاعة');scan(o,u,'pickup',p.scanMethod);u.budget-=prepaid;writeUser(u);o.goodsPaid=prepaid;o.pickupAt=now();change(o,u,'received','تم الاستلام بعد الفحص والدفع');cash(o,u.id,-prepaid,'دفع قيمة البضاعة للمرسل');cash(o,o.merchant,prepaid,'استلام قيمة البضاعة من المندوب');
 }
 else if(action==='transit'){must(assigned&&o.status==='received','استلم الطلب أولاً');change(o,u,'transit','بدأ التوصيل إلى الزبون');}
 else if(action==='customer_arrive'){must(assigned&&['transit','retry'].includes(o.status),'إجراء غير متاح');if(o.status==='retry')must(o.retryApproved,'موعد المحاولة بانتظار موافقة التاجر');change(o,u,'at_customer','وصل المندوب إلى الزبون');}
 else if(action==='deliver'){must(assigned&&o.status==='at_customer','أكد الوصول إلى الزبون أولاً');must(p.confirmed===true,'أكد التسليم والتحصيل');must(clean(p.proof,300).length>=8,'أدخل وصف إثبات التسليم؛ خدمة SMS غير مربوطة في النسخة المحلية');const collected=o.amount+(o.feePayer==='customer'?o.fee:0);u.budget+=collected;writeUser(u);o.collected=collected;o.deliveredAt=now();o.proof=clean(p.proof,300);o.settled=o.feePayer==='customer'&&o.kind!=='free';change(o,u,'delivered','تم التسليم والتحصيل بتأكيد محلي موثق');cash(o,u.id,collected,'تحصيل من الزبون');commission(o);}
 else if(action==='fail'){must(assigned&&['transit','at_customer','retry'].includes(o.status),'إجراء غير متاح');must(clean(p.reason),'حدد سبب التعذر');o.attempts++;o.failureReason=clean(p.reason);change(o,u,'failed','تعذر التسليم: '+o.failureReason);record('failure',u.id,oid,{reason:o.failureReason});}
 else if(action==='retry'){must(assigned&&o.status==='failed'&&o.attempts<c.maxAttempts,'لا يمكن إضافة محاولة أخرى');must(Date.parse(p.when)>Date.now(),'حدد موعداً مستقبلياً');o.retryAt=new Date(p.when).toISOString();o.retryApproved=false;change(o,u,'retry','اقتراح موعد محاولة جديدة بانتظار موافقة التاجر');}
 else if(action==='approve_retry'){must(own&&o.status==='retry','إجراء غير متاح');o.retryApproved=true;log(o,u,'وافق التاجر على موعد المحاولة');note(o.courier,o,'وافق التاجر على موعد المحاولة');}
 else if(action==='return'){must((assigned||own)&&['failed','retry'].includes(o.status),'الإرجاع يبدأ بعد تعذر التسليم');change(o,u,'return_pending','تقرر إرجاع الشحنة');}
 else if(action==='return_start'){must(assigned&&['return_pending','partial_pending'].includes(o.status),'إجراء غير متاح');o.returnCode=String(crypto.randomInt(100000,1000000));change(o,u,'returning','المندوب يعيد الشحنة إلى التاجر');}
 else if(action==='return_arrive'){must(assigned&&o.status==='returning','إجراء غير متاح');must(!o.returnArrived,'تم تأكيد وصول المرتجع مسبقاً');must(o.returnCode&&String(p.code)===o.returnCode,'رمز المرتجع غير صحيح');scan(o,u,'return',p.scanMethod);o.returnArrived=true;log(o,u,'وصل المندوب بالمرتجع');note(o.merchant,o,'وصل المرتجع للفحص');}
 else if(action==='receive_return'){must(own&&o.status==='returning'&&o.returnArrived,'انتظر وصول المرتجع');must(p.inspected===true,'أكد فحص القطع المرتجعة');o.returnReceived=true;log(o,u,'أكد التاجر استلام المرتجع؛ التسوية ما زالت مفتوحة');}
 else if(action==='settle_return'){must(assigned&&o.status==='returning'&&o.returnReceived,'يجب تأكيد التاجر استلام المرتجع أولاً');must(p.confirmed===true,'أكد استرداد قيمة البضاعة');const goods=o.goodsPaid?o.amount-(o.partial?.amount||0):0;const paid=amount(p.fees,'الأجور المسواة',2000000);must(paid===o.fee+o.returnFee,'يجب تسوية أجرة الذهاب والراجع كاملة قبل الإغلاق');u.budget+=goods+paid;writeUser(u);o.settled=true;o.returnedAt=now();change(o,u,'returned',o.partial?'أُغلق الطلب بنتيجة تسليم جزئي بعد الإرجاع والتسوية':'تم الإرجاع وتسوية البضاعة والأجور');cash(o,u.id,goods+paid,'استرداد قيمة المرتجع وتسوية الأجور');cash(o,o.merchant,-goods-paid,'رد قيمة المرتجع وتسوية الأجور (تأكيد محلي)');}
 else if(action==='settle_delivery'){must(assigned&&o.status==='delivered'&&!o.settled,'لا توجد تسوية تسليم مفتوحة');must(p.confirmed===true,'أكد تسوية المبالغ مع المرسل');const merchantFee=o.feePayer==='merchant'?o.fee:0;const remittance=o.kind==='free'?o.amount:0;u.budget+=merchantFee-remittance;writeUser(u);cash(o,u.id,merchantFee-remittance,'تسوية مع المرسل بعد التسليم');cash(o,o.merchant,remittance-merchantFee,'تسوية بعد التسليم');o.settled=true;log(o,u,'اكتملت التسوية مع المرسل');}
 else if(action==='partial_propose'){must(c.partialEnabled&&o.kind!=='free','التسليم الجزئي يحتاج سياسة معتمدة للشحنات التجارية');must(assigned&&o.status==='at_customer','إجراء غير متاح');const units=amount(p.count),value=amount(p.amount);must(units>0&&units<o.count&&value>0&&value<o.amount,'حدد عدداً وقيمة أقل من كامل الطلب');o.partial={count:units,amount:value,approved:false};log(o,u,'اقتراح تسليم جزئي بانتظار موافقة التاجر');note(o.merchant,o,'طلب موافقة على التسليم الجزئي');}
 else if(action==='partial_approve'){must(own&&o.partial&&!o.partial.approved&&o.status==='at_customer','إجراء غير متاح');o.partial.approved=true;log(o,u,'وافق التاجر على التسليم الجزئي');note(o.courier,o,'تمت الموافقة على التسليم الجزئي');}
 else if(action==='partial_confirm'){must(assigned&&o.partial?.approved&&o.status==='at_customer','تحتاج موافقة التاجر');must(p.confirmed===true,'أكد تحصيل قيمة الجزء المسلم');u.budget+=o.partial.amount;writeUser(u);cash(o,u.id,o.partial.amount,'تحصيل قيمة الجزء المسلم دون أجور');change(o,u,'partial_pending','تم التسليم جزئياً؛ بانتظار إرجاع المتبقي');}
 else if(action==='rate'){must((own||assigned)&&closed.includes(o.status)&&o.status!=='cancelled'&&o.settled,'التقييم متاح بعد إكمال الطلب والتسوية');must(!records('rating').some(x=>x.owner===u.id&&x.orderId===oid),'قيّمت هذا الطلب سابقاً');const stars=amount(p.stars);must(stars>=1&&stars<=5,'التقييم بين1 و5');record('rating',u.id,oid,{target:own?o.courier:o.merchant,stars,text:clean(p.text,500)});}
 else if(action==='chat'){must((own||assigned)&&o.courier,'المحادثة متاحة بعد الحجز');must(clean(p.text,2000),'أدخل رسالة');record('chat',u.id,oid,{name:u.name,text:clean(p.text,2000)});note(own?o.courier:o.merchant,o,'رسالة جديدة في محادثة الطلب');}
 else fail('الإجراء غير معروف');writeOrder(o);return redact(u,o);
 });}
function create(u,data){return tx(()=>{must(u.role==='merchant'&&u.approved,'إنشاء الطلبات لحساب التاجر المعتمد');const o=normalizeOrder(data,u);if(data.publish){o.status='published';o.publishedAt=now();}log(o,u,data.publish?'أنشئ ونُشر الطلب':'حُفظ الطلب دون نشر');writeOrder(o);const current=user(u.id);rememberOrderPlaces(current,o,id);writeOrder(o);writeUser(current);return o;});}
const documentKeys=['residenceFront','nationalFront','nationalBack','licenseFront','licenseBack'];
function validateDocuments(value){const docs={};for(const key of documentKeys){const image=value?.[key];must(typeof image==='string'&&image.length<=600000&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/]+={0,2}$/.test(image),'أكمل صور بطاقة السكن والبطاقة الوطنية وإجازة السوق');docs[key]=image;}return docs;}
function register(p){return tx(()=>{must(['merchant','courier'].includes(p.role),'الدور غير مسموح');must((p.password||'').length>=8,'كلمة المرور ثمانية أحرف على الأقل');const number=phone(p.phone);must(!db.prepare('SELECT id FROM users WHERE phone=? AND role=?').get(number,p.role),'رقم الهاتف مسجل لهذا الدور');must(clean(p.name),'أدخل الاسم');if(p.role==='merchant'){must(['shop','warehouse'].includes(p.activity),'التجارة الإلكترونية ستتاح لاحقاً');must(Array.isArray(p.photos)&&p.photos.length===2,'أضف صورة داخلية وأخرى خارجية');}if(p.role==='courier'){must(p.confirmPassword===p.password,'كلمة المرور وتأكيدها غير متطابقين');validateDocuments(p.documents);}if(p.role==='courier')must(['motorcycle','sedan','truck','refrigerated'].includes(p.vehicle)&&clean(p.plate),'أكمل نوع المركبة ورقمها');const uid=id(p.role==='merchant'?'MER':'COU');const profile={name:clean(p.name,80),province:clean(p.province,50),area:clean(p.area,80),address:clean(p.address),location:location(p.location),activity:p.activity,vehicle:p.vehicle,plate:clean(p.plate,40),photos:(p.photos||[]).filter(s=>/^data:image\/(jpeg|png|webp);base64,/.test(s)).slice(0,2),...(p.role==='courier'?{documents:validateDocuments(p.documents)}:{}),walletId:'W-'+uid,available:false,budget:0,radius:3};must(profile.province&&profile.area&&profile.address,'أكمل العنوان');if(p.role==='merchant')must(profile.photos.length===2,'الصور المرفقة غير صالحة');db.prepare('INSERT INTO users VALUES(?,?,?,?,?,1)').run(uid,number,p.role,hash(p.password),JSON.stringify(profile));record('audit',uid,'',{text:'إنشاء حساب'});return publicUser(user(uid));});}
function login(p){must(['merchant','courier'].includes(p.role),'الدور غير مسموح');const number=phone(p.phone);const r=db.prepare('SELECT * FROM users WHERE phone=? AND role=?').get(number,p.role);must(r&&check(String(p.password||''),r.password),'بيانات الدخول غير صحيحة');const token=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(token,r.id,Date.now()+86400000);return {token,user:publicUser(user(r.id))};}
function session(token){const r=db.prepare('SELECT user_id FROM sessions WHERE token=? AND expires>?').get(token||'',Date.now());const u=r?user(r.user_id):null;return u&&['merchant','courier'].includes(u.role)?u:null;}
function update(u,p){return tx(()=>{u=user(u.id);
 if(p.action==='readiness'){must(u.role==='courier'&&u.approved,'غير متاح');u.available=!!p.available;if(u.available){u.budget=amount(p.budget,'الميزانية');u.radius=Number(p.radius);must(u.radius>0&&u.radius<=100,'النطاق بين1 و100 كم');u.location=location(p.location);}writeUser(u);record('audit',u.id,'',{text:'تحديث الجاهزية والميزانية'});}
 else if(p.action==='location'){must(u.role==='courier','غير متاح');u.location=location(p.location);u.locationAt=now();writeUser(u);}
 else if(p.action==='preferences'){u.motivational=!!p.motivational;writeUser(u);}
 else if(p.action==='profile'){must(!unresolved(u.id),'تعديل الملف غير متاح قبل إكمال الطلبات والمرتجعات والتسويات');const changes={name:clean(p.name,80),province:clean(p.province,50),area:clean(p.area,80),address:clean(p.address),phone2:p.phone2?phone(p.phone2):'',location:location(p.location)};must(changes.name&&changes.address&&changes.province&&changes.area,'أكمل البيانات');Object.assign(u,changes);writeUser(u);record('audit',u.id,'',{text:'تحديث الملف الشخصي'});}
 else fail('إجراء غير معروف');return publicUser(u);});}
function seed(){if(users().length)return;for(const [role,prefix,name,p] of [['merchant','MER','متجر الأناقة للملابس','07700000001'],['courier','COU','حيدر جاسم','07700000002']]){const uid=prefix+'-DEMO';db.prepare('INSERT INTO users VALUES(?,?,?,?,?,1)').run(uid,p,role,hash('WaselDemo2026!'),JSON.stringify({name,province:'بغداد',area:'الكرادة',address:'الكرادة داخل — قرب المسرح الوطني',location:{lat:33.300,lng:44.430},walletId:'W-'+uid,vehicle:'sedan',plate:'بغداد 12345',available:role==='courier',budget:500000,radius:5,customers:[],demo:true}));}
 const merchant=user('MER-DEMO');const o=normalizeOrder({amount:100000,count:2,weight:3.5,length:35,width:25,height:20,nature:'fragile',vehicle:'sedan',fee:5000,returnFee:3000,feePayer:'customer',recipient:{name:'نور الهدى صالح',phone:'07700000005',area:'المنصور',address:'شارع14 رمضان',landmark:'قرب الجامع'},notes:'الاتصال قبل الوصول'},merchant);o.id='ORD-DEMO-1001';o.status='published';o.demo=true;o.publishedAt=new Date(Date.now()-30*60000).toISOString();o.history=[{at:now(),actor:merchant.id,status:'published',text:'طلب تجريبي لاختبار دورة العمل'}];writeOrder(o);
}
// One-time migration of the working database; the pre-restructure backup stays intact.
db.exec('CREATE TABLE IF NOT EXISTS migrations(id TEXT PRIMARY KEY)');
if(!db.prepare('SELECT id FROM migrations WHERE id=?').get('two-roles-v1'))tx(()=>{
 db.exec("DELETE FROM sessions WHERE user_id IN (SELECT id FROM users WHERE role NOT IN ('merchant','courier')); DELETE FROM records WHERE owner IN (SELECT id FROM users WHERE role NOT IN ('merchant','courier')); DELETE FROM users WHERE role NOT IN ('merchant','courier'); DELETE FROM records WHERE kind IN ('ticket','support_reply','review');");
 for(const u of users()){delete u.pendingProfile;writeUser(u);}
 // Keep historical wallet amounts while detaching obsolete funding actors.
 for(const r of db.prepare('SELECT id,body FROM records').all()){const body=JSON.parse(r.body);if(body.outlet){delete body.outlet;body.reason='رصيد سابق';db.prepare('UPDATE records SET body=? WHERE id=?').run(JSON.stringify(body),r.id);}}
 db.prepare('INSERT INTO migrations VALUES(?)').run('two-roles-v1');
});
seed();
module.exports={expire,db,statuses,config,user,users,orders,order,records,record,view,create,action,register,login,session,update,fail,phone,publicUser,wallet};
