const demoDocuments=require('./demo-documents.cjs');
'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'wasel-tests-'));process.env.WASEL_DATA_DIR=dir;
const d=require('./domain.cjs');let passed=0;
const test=(name,fn)=>{fn();passed++;console.log('PASS '+name);};
const m=d.user('MER-DEMO'),c=d.user('COU-DEMO');
function data(extra={}){return {amount:100000,count:2,weight:2,length:20,width:20,height:20,nature:'normal',vehicle:'sedan',baseFee:5000,fee:5000,returnFee:3000,feePayer:'customer',recipient:{name:'عميل تجريبي',phone:'07712345678',area:'المنصور',address:'شارع تجريبي'},...extra};}
function pickup(o){d.action(c,o.id,'reserve');d.action(c,o.id,'arrive');d.action(c,o.id,'pickup',{code:d.order(o.id).handoverCode,inspected:true,paid:true});d.action(c,o.id,'transit');}
function setConfig(values){d.db.prepare('INSERT INTO config VALUES(1,?) ON CONFLICT(id) DO UPDATE SET body=excluded.body').run(JSON.stringify({...d.config(),...values}));}
try{
test('normalize Iraqi phone and reject Korek for account roles',()=>{assert.equal(d.phone('+964 770 123 4567'),'07701234567');assert.throws(()=>d.phone('07501234567'));});
test('password login/session and wrong password',()=>{const l=d.login({role:'merchant',phone:m.phone,password:'WaselDemo2026!'});assert.equal(d.session(l.token).id,m.id);assert.throws(()=>d.login({role:'merchant',phone:m.phone,password:'wrong'}));});
test('fees and refrigerated vehicle validation',()=>{assert.throws(()=>d.create(m,data({returnFee:6000})));assert.throws(()=>d.create(m,data({nature:'cold',vehicle:'sedan'})));assert.throws(()=>d.create(m,data({service:'vip',baseFee:5000,fee:5000})));});
let first=d.create(m,data({publish:true,feePayer:'merchant'}));
test('customer privacy before handover',()=>{const available=d.view(c).orders.find(o=>o.id===first.id);assert.equal(available.recipient.phone,undefined);assert.equal(available.recipient.name,undefined);});
test('exclusive reservation per order and multiple normal reservations',()=>{d.action(c,first.id,'reserve');assert.throws(()=>d.action(c,first.id,'reserve'));const second=d.create(m,data({publish:true}));d.action(c,second.id,'reserve');assert.equal(d.order(second.id).courier,c.id);d.action(m,second.id,'cancel');});
test('merchant edits release booking without courier penalty',()=>{const n=d.records('cancellation').length;d.action(m,first.id,'edit',data({amount:80000,feePayer:'merchant'}));assert.equal(d.order(first.id).status,'published');assert.equal(d.order(first.id).courier,null);assert.equal(d.records('cancellation').length,n);});
test('handover verifies code and financial budget',()=>{d.action(c,first.id,'reserve');d.action(c,first.id,'arrive');const balance=d.user(c.id).budget;assert.throws(()=>d.action(c,first.id,'pickup',{code:'000000',inspected:true,paid:true}));assert.equal(d.user(c.id).budget,balance);d.action(c,first.id,'pickup',{code:d.order(first.id).handoverCode,inspected:true,paid:true});assert.equal(d.user(c.id).budget,balance-80000);assert.equal(d.view(c).orders.find(o=>o.id===first.id).recipient.phone,'07712345678');assert.throws(()=>d.action(m,first.id,'cancel'));});
test('merchant-paid fee excluded from customer collection',()=>{d.action(c,first.id,'transit');d.action(c,first.id,'customer_arrive');const before=d.user(c.id).budget;d.action(c,first.id,'deliver',{confirmed:true,proof:'إثبات تجريبي لتسليم كامل'});assert.equal(d.user(c.id).budget,before+80000);assert.equal(d.order(first.id).settled,false);d.action(c,first.id,'settle_delivery',{confirmed:true});assert.equal(d.order(first.id).settled,true);});
test('single rating per actor per complete order',()=>{d.action(m,first.id,'rate',{stars:5,text:'جيد'});assert.throws(()=>d.action(m,first.id,'rate',{stars:4}));});
let returned=d.create(m,data({publish:true}));pickup(returned);
test('retry requires merchant approval and remains in custody',()=>{d.action(c,returned.id,'fail',{reason:'عدم الرد'});d.action(c,returned.id,'retry',{when:new Date(Date.now()+3600000).toISOString()});assert.throws(()=>d.action(c,returned.id,'customer_arrive'));d.action(m,returned.id,'approve_retry');d.action(c,returned.id,'customer_arrive');d.action(c,returned.id,'fail',{reason:'رفض الاستلام'});});
test('return receipt does not close order before financial settlement',()=>{d.action(c,returned.id,'return');d.action(c,returned.id,'return_start');d.action(c,returned.id,'return_arrive',{code:d.order(returned.id).returnCode});d.action(m,returned.id,'receive_return',{inspected:true});assert.equal(d.order(returned.id).settled,false);assert.throws(()=>d.update(m,{action:'profile',name:'تعديل'}));assert.throws(()=>d.action(c,returned.id,'settle_return',{confirmed:true,fees:0}));d.action(c,returned.id,'settle_return',{confirmed:true,fees:8000});assert.equal(d.order(returned.id).status,'returned');assert.equal(d.order(returned.id).settled,true);});
test('VIP exclusivity until completed',()=>{const vip=d.create(m,data({publish:true,service:'vip',baseFee:5000,fee:8000}));pickup(vip);const next=d.create(m,data({publish:true}));assert.throws(()=>d.action(c,next.id,'reserve'));d.action(c,vip.id,'customer_arrive');d.action(c,vip.id,'deliver',{confirmed:true,proof:'تم التحقق من التسليم محلياً'});});
test('fee offers require elapsed duration and sender approval',()=>{setConfig({offerAfterMinutes:0});const offerOrder=d.create(m,data({publish:true}));d.action(c,offerOrder.id,'offer',{fee:7000});assert.equal(d.order(offerOrder.id).status,'published');const offer=d.records('offer').find(r=>r.orderId===offerOrder.id);d.action(m,offerOrder.id,'accept_offer',{offer:offer.id});assert.equal(d.order(offerOrder.id).fee,7000);assert.equal(d.order(offerOrder.id).status,'reserved');d.action(m,offerOrder.id,'cancel');});
test('partial delivery requires policy and merchant consent',()=>{const o=d.create(m,data({publish:true}));pickup(o);d.action(c,o.id,'customer_arrive');assert.throws(()=>d.action(c,o.id,'partial_propose',{count:1,amount:60000}));setConfig({partialEnabled:true});d.action(c,o.id,'partial_propose',{count:1,amount:60000});assert.throws(()=>d.action(c,o.id,'partial_confirm',{confirmed:true}));d.action(m,o.id,'partial_approve');d.action(c,o.id,'partial_confirm',{confirmed:true});d.action(c,o.id,'return_start');d.action(c,o.id,'return_arrive',{code:d.order(o.id).returnCode});d.action(m,o.id,'receive_return',{inspected:true});d.action(c,o.id,'settle_return',{confirmed:true,fees:8000});assert.equal(d.order(o.id).partial.amount,60000);assert.equal(d.order(o.id).settled,true);});
test('extension once, expiry republishes without accepting late actions',()=>{const o=d.create(m,data({publish:true,amount:1000}));d.action(c,o.id,'reserve');const original=Date.parse(d.order(o.id).deadline);d.action(c,o.id,'extend',{minutes:Math.ceil(d.order(o.id).originalMinutes/2)});assert(Date.parse(d.order(o.id).deadline)>original);assert.throws(()=>d.action(c,o.id,'extend'));const expired=d.order(o.id);expired.deadline=new Date(Date.now()-1000).toISOString();d.db.prepare('UPDATE orders SET body=? WHERE id=?').run(JSON.stringify(expired),o.id);assert.throws(()=>d.action(c,o.id,'arrive'));assert.equal(d.order(o.id).status,'published');});
test('repeated cancellations restrict new bookings',()=>{for(let i=0;i<2;i++){const o=d.create(m,data({publish:true,amount:1000}));d.action(c,o.id,'reserve');d.action(c,o.id,'release',{reason:'سبب اختبار'});}assert(Date.parse(d.user(c.id).restrictedUntil)>Date.now());const o=d.create(m,data({publish:true,amount:1000}));assert.throws(()=>d.action(c,o.id,'reserve'));});

test('only merchant and courier can authenticate or register',()=>{assert.deepEqual(d.users().map(u=>u.role).sort(),['courier','merchant']);for(const role of ['admin','outlet']){assert.throws(()=>d.login({role,phone:'07700000003',password:'WaselDemo2026!'}));assert.throws(()=>d.register({role}));}assert.equal(d.admin,undefined);assert.equal(d.topup,undefined);});
test('state has no removed role data',()=>{const state=d.view(m);for(const key of ['users','audit','reviews','outletTransactions','tickets'])assert.equal(key in state,false);});
test('new account is usable and profile edits preserve identity',()=>{const u=d.register({role:'courier',documents:demoDocuments(),confirmPassword:'Password123!',name:'مندوب جديد',phone:m.phone,password:'Password123!',province:'بغداد',area:'الكرادة',address:'عنوان',location:{lat:33.3,lng:44.43},vehicle:'sedan',plate:'123'});assert(u.approved);assert.notEqual(u.id,m.id);d.update(u,{action:'profile',name:'اسم معدل',province:'بغداد',area:'المنصور',address:'عنوان جديد',location:{lat:33.3,lng:44.43}});assert.equal(d.user(u.id).name,'اسم معدل');assert.equal(d.user(u.id).walletId,u.walletId);d.update(u,{action:'readiness',available:true,budget:10000,radius:5,location:u.location});assert(d.user(u.id).available);});
test('chat stays scoped to its own order',()=>{d.action(m,returned.id,'chat',{text:'رسالة مرتبطة بالراجع'});assert.equal(d.records('chat').filter(r=>r.orderId===first.id).length,0);});

test('courier documents and password confirmation are mandatory',()=>{const p={role:'courier',name:'فحص المستمسكات',phone:'07712349999',password:'Password123!',confirmPassword:'Password123!',province:'بغداد',area:'الكرادة',address:'عنوان تجريبي',location:{lat:33.3,lng:44.43},vehicle:'sedan',plate:'123'};assert.throws(()=>d.register(p));assert.throws(()=>d.register({...p,documents:demoDocuments(),confirmPassword:'different'}));assert.throws(()=>d.register({...p,documents:{...demoDocuments(),licenseBack:'data:text/html;base64,QQ=='}}));assert.throws(()=>d.register({...p,documents:{...demoDocuments(),nationalFront:'data:image/png;base64,'+'A'.repeat(600001)}}));const registered=d.register({...p,documents:demoDocuments()});assert.equal(registered.documents,undefined);assert.equal(Object.keys(d.user(registered.id).documents).length,5);assert.equal(d.view(d.user(registered.id)).user.documents,undefined);assert.equal(d.login({role:'courier',phone:p.phone,password:p.password}).user.documents,undefined);});
test('return verification is private and recorded separately from settlement',()=>{const o=d.order(returned.id);assert.match(o.returnCode,/^\d{6}$/);assert.equal(d.view(c).orders.find(x=>x.id===o.id).returnCode,undefined);const scans=o.history.filter(x=>x.action==='scan');assert(scans.some(x=>x.kind==='pickup'));assert(scans.some(x=>x.kind==='return'));assert(!JSON.stringify(scans).includes(o.returnCode));assert.throws(()=>d.action(c,o.id,'return_arrive',{code:o.returnCode}));});
console.log(`\n${passed} domain checks passed. Test database isolated: ${dir}`);
}finally{d.db.close();}
