// Synthetic, browser-only data for designing and testing the Vue interface.
export const statuses = {
  draft: "محفوظ",
  published: "منشور",
  reserved: "بانتظار المندوب",
  approaching: "المندوب في الطريق إلى التاجر",
  arrived: "المندوب وصل",
  waiting: "بانتظار الاستلام",
  received: "تم الاستلام",
  transit: "قيد التوصيل",
  at_customer: "وصل إلى الزبون",
  delivered: "تم التسليم",
  failed: "تعذر التسليم",
  retry: "إعادة محاولة التوصيل",
  return_pending: "بانتظار الإرجاع",
  returning: "قيد الإرجاع",
  partial_pending: "تسليم جزئي — بانتظار إرجاع المتبقي",
  returned: "تم الإرجاع",
  cancelled: "ملغي",
  completed: "منتهي",
};
export function createDemoData() {
  const location = { lat: 33.3, lng: 44.43 };
  const merchant = {
    id: "MER-DEMO",
    role: "merchant",
    name: "متجر الأناقة للملابس",
    phone: "07700000001",
    province: "بغداد",
    area: "الكرادة",
    address: "الكرادة داخل — قرب المسرح الوطني",
    location,
    approved: true,
    demo: true,
    walletId: "W-MER-DEMO",
    customers: [],
    motivational: true,
  };
  const courier = {
    ...merchant,
    id: "COU-DEMO",
    role: "courier",
    name: "حيدر جاسم",
    phone: "07700000002",
    walletId: "W-COU-DEMO",
    vehicle: "sedan",
    plate: "بغداد 12345",
    available: true,
    budget: 500000,
    radius: 5,
  };
  const at = new Date().toISOString();
  const sampleRecipients = [
    [
      "أحمد سامر",
      "المنصور",
      "شارع الرواد — بناية الربيع، الطابق الثاني",
      33.32,
      44.35,
    ],
    [
      "زينب علي",
      "زيونة",
      "شارع الربيعي — قرب مجمع المحلات، دار 12",
      33.33,
      44.46,
    ],
    ["مصطفى كريم", "الجادرية", "شارع الجامعة — محلة 21، زقاق 8", 33.28, 44.4],
    [
      "نور حسين",
      "الكرادة",
      "الكرادة داخل — قرب مكتبة الندى، دار 7",
      33.3,
      44.43,
    ],
    ["حسن ماجد", "المنصور", "شارع 14 رمضان — مجمع النخيل، محل 4", 33.33, 44.36],
    [
      "مريم عادل",
      "زيونة",
      "شارع فلسطين — قرب حديقة الحي، دار 25",
      33.34,
      44.45,
    ],
    [
      "علي سجاد",
      "الجادرية",
      "شارع الوزراء — بناية الياسمين، شقة 3",
      33.29,
      44.41,
    ],
    [
      "فاطمة رائد",
      "الكرادة",
      "الكرادة خارج — شارع العطار، دار 18",
      33.31,
      44.42,
    ],
    ["عمر قاسم", "المنصور", "حي دراغ — شارع الزيتون، دار 9", 33.32, 44.34],
    ["سارة مهند", "زيونة", "شارع الربيعي — مجمع الزهور، شقة 6", 33.32, 44.45],
    ["يوسف حازم", "الجادرية", "قرب جسر الجادرية — زقاق 5، دار 14", 33.27, 44.4],
    [
      "رقية وسام",
      "الكرادة",
      "شارع الصناعة — بناية دجلة، الطابق الأول",
      33.31,
      44.44,
    ],
  ];
  const orders = Array.from(
    { length: 54 },
    (_, index) => Object.keys(statuses)[index % 18],
  ).map((status, index) => ({
    id: "ORD-DEMO-" + String(index + 1).padStart(4, "0"),
    merchant: merchant.id,
    courier: ["draft", "published", "cancelled"].includes(status)
      ? null
      : courier.id,
    status,
    kind: "merchant",
    service: index % 3 === 2 ? "vip" : "normal",
    collection: "none",
    nature: "normal",
    vehicle: "sedan",
    amount: 20000 + index * 2500,
    count: 3,
    weight: 2,
    length: 20,
    width: 20,
    height: 20,
    baseFee: 5000,
    fee: 5000,
    returnFee: 3000,
    feePayer: "customer",
    sender: { ...merchant },
    recipient: {
      name: sampleRecipients[index % sampleRecipients.length][0],
      phone: "0778800" + String(index + 1).padStart(4, "0"),
      province: "بغداد",
      area: sampleRecipients[index % sampleRecipients.length][1],
      address: sampleRecipients[index % sampleRecipients.length][2],
      location: {
        lat: sampleRecipients[index % sampleRecipients.length][3],
        lng: sampleRecipients[index % sampleRecipients.length][4],
      },
    },
    notes:
      [
        "ملابس جاهزة — الاتصال قبل الوصول",
        "عناية بالبشرة — يرجى إبقاء العبوة مستقيمة",
        "أحذية — التسليم بعد الساعة الرابعة",
        "هدايا مغلفة — التعامل بحذر",
      ][index % 4] + " (بيانات وهمية للفحص)",
    demo: true,
    createdAt: at,
    updatedAt: at,
    settled: ["delivered", "returned", "cancelled", "completed"].includes(
      status,
    ),
    goodsPaid: ![
      "draft",
      "published",
      "reserved",
      "approaching",
      "arrived",
      "waiting",
      "cancelled",
    ].includes(status),
    handoverCode: "123456",
    attempts: 1,
    retryAt:
      status === "retry" ? new Date(Date.now() + 86400000).toISOString() : null,
    retryApproved: false,
    partial:
      status === "partial_pending"
        ? { count: 1, amount: 5000, approved: true }
        : null,
    returnArrived: status === "returning",
    returnReceived: false,
    history: [
      {
        at,
        actor: "DEMO",
        text: "بيانات تجريبية — " + statuses[status],
        status,
      },
    ],
  }));
  merchant.customers = orders.slice(0, 3).map((o) => o.recipient);
  const ledger = [
    {
      id: "W1",
      owner: merchant.id,
      amount: 175000,
      reason: "إضافة تجريبية",
      at,
    },
    { id: "W2", owner: merchant.id, amount: -12500, reason: "خصم تجريبي", at },
    {
      id: "W3",
      owner: courier.id,
      amount: 110000,
      reason: "إضافة تجريبية",
      at,
    },
    { id: "W4", owner: courier.id, amount: -8500, reason: "خصم تجريبي", at },
  ];
  return {
    version: 1,
    expandedDemoCatalog: true,
    users: [merchant, courier],
    orders,
    ledger,
    cashLedger: [],
    messages: [],
    ratings: [],
    offers: [],
    notifications: [
      {
        id: "N1",
        owner: merchant.id,
        text: "أهلاً بك في حساب التاجر التجريبي",
        at,
      },
      {
        id: "N2",
        owner: courier.id,
        text: "أهلاً بك في حساب المندوب التجريبي",
        at,
      },
    ],
    lastByRole: { merchant: merchant.id, courier: courier.id },
  };
}
export const settings = {
  freeService: true,
  commission: 0,
  subscription: 0,
  vipSurcharge: 3000,
  partialEnabled: true,
  offerAfterMinutes: 10,
  arrivalBuffer: 30,
  arrivalRadiusKm: 0.3,
  penaltiesEnabled: false,
  cancelSecondMinutes: 60,
  failureThreshold: 3,
  failureRestrictionMinutes: 180,
  waitMinutes: 15,
  feesStartAt: "",
  maxCarried: 0,
  cancelThirdMinutes: 180,
  commissionMode: "fixed",
  freeCommission: 0,
  vipCommission: 0,
  returnCommission: false,
  extensionPercent: 50,
  vehicleKg: { motorcycle: 20, sedan: 100, truck: 2000, refrigerated: 1000 },
  vehicleCm: { motorcycle: 80, sedan: 150, truck: 500, refrigerated: 400 },
};
