import { createApp } from "vue";
import App from "./App.vue";
import "../styles.css";
import "../app.css";
import "../platform.css";
import "../courier-registration.css";
import "../theme.css";
import { initTheme } from "./services/theme.js";
import { initInteractions } from "./services/interaction.js";
initTheme();
createApp(App).mount("#wasel-root");
initInteractions();
